name: Create and publish a Docker image

on:
  push:
    branches:
      - master

env:
  REGISTRY: ghcr.io

jobs:
  build-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      # https://github.com/marketplace/actions/checkout
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: (cd web && npm install)
      - name: Build Boot Jar
        run: ./gradlew graphql:bootJar

      # https://github.com/marketplace/actions/docker-login
      - name: Log in to the Container registry
        uses: docker/login-action@v2.1.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      # https://github.com/marketplace/actions/docker-metadata-action
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4.3.0
        with:
          #          images: ${{ env.REGISTRY }}/${{ github.actor }}/solarthing-server
          images: ${{ env.REGISTRY }}/wildmountainfarms/solarthing-server
          tags: |
            type=raw,value=edge,enable=${{ github.ref == 'refs/heads/master' }}
      # https://github.com/marketplace/actions/docker-setup-buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      # https://github.com/marketplace/actions/build-and-push-docker-images
      - name: Build and push Docker image
        uses: docker/build-push-action@v4.0.0
        with:
          context: .
          file: docker/solarthing-server/Dockerfile
          build-args: |
            BOOT_JAR=graphql/build/libs/graphql-0.0.1-SNAPSHOT.jar
          push: true
          platforms: linux/amd64,linux/arm/v7,linux/arm64/v8,linux/ppc64le,linux/s390x
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
